version: "3"
services:
  server-docker:
    image: server-docker
    ports:
      - "3001:3001"
    depends_on:
      - mongo
    links:
      - mongo
      # theis link was just added
  mongo:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - data:/data/db
volumes:
  data:
    driver: local
