version: "3.8"

services:
  server-docker:
    image: server-docker
    container_name: server-docker
    # ports:
    #   - "3000:3000"
    depends_on:
      - mongo
    links:
      - mongo
    restart: unless-stopped
    stdin_open: true
    tty: true
  mongo:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - data:/data/db
  caddy:
    image: caddy:latest
    container_name: caddy
    restart: unless-stopped
    ports:
      - "80:80"
    volumes:
      - $PWD/Caddyfile:/etc/caddy/Caddyfile
      - caddy_data:/data
      - caddy_config:/config
volumes:
  caddy_data:
  caddy_config:
  data:
